version: '3'

services:

    app:
        build: .
        container_name: app
        entrypoint: dockerize -template ./.docker/app/.env.example:.env -wait tcp://db:3306 -timeout 100s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=app
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - fazendinha
        depends_on:
            - db
            # - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - fazendinha
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - fazendinha

    # redis:
    #     image: redis:alpine
    #     container_name: redis
    #     expose:
    #         - 6379
    #     networks:
    #         - fazendinha

networks:
    fazendinha:
        driver: bridge
